spring:
  application:
    name: ollama-study
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5-coder:7b
      init:
        pull-model-strategy: never
    openai:
      api-key: ${SILICONFLOW_API_KEY}
      base-url: https://api.moonshot.cn
      chat:
        options:
          model: moonshot-v1-8k
#        api-key:
#        base-url: https://api.siliconflow.cn

    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "This server provides weather information tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true


logging:
  level:
    org.springframework.ai: DEBUG